### ISSUE TITLE
JVM_Bind on simple target connection try

### ISSUE THREAD

**Issue by romanman** [htwg/UCE#3]
Hey guys , 

Thanks for glorious lib, 
some small problem I am trying to establish simple
hole punching, for that I have started mediator
on some server and trying to connect to it by 
that code: 

```
        UnsecureTargetSideConnectionEstablishment utsce = new UnsecureTargetSideConnectionEstablishment();
        utsce.establishConnection("11", DefaultConnectionConfiguration.getInstance());
```

I see that the connection is touching the mediator for sure because
I get there output like that: 

```
DEBUG [pool-1-thread-1] 2014-09-24 15:14:21,292 (HandleMessageTask.java:82) - Got message from Socket[addr=/85.178.50.229,port=64861,localport=30303]
DEBUG [pool-1-thread-1] 2014-09-24 15:14:21,295 (DefaultRegisterHandling.java:70) - User 11 added or updated

```

but on the client side I am getting this: 

```
ERROR [main] 2014-09-24 17:13:16,192 (DeterminingTcpNatMapping.java:134) - Exception eccured while executing test
java.net.BindException: Address already in use: JVM_Bind
    at java.net.DualStackPlainSocketImpl.bind0(Native Method)
    at java.net.DualStackPlainSocketImpl.socketBind(DualStackPlainSocketImpl.java:106)
    at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:376)
    at java.net.PlainSocketImpl.bind(PlainSocketImpl.java:190)
    at java.net.Socket.bind(Socket.java:631)
    at de.fhkn.in.uce.connectivitymanager.investigator.DeterminingTcpNatMapping.executeTestRun(DeterminingTcpNatMapping.java:127)
    at de.fhkn.in.uce.connectivitymanager.investigator.DeterminingTcpNatMapping.executeTestI(DeterminingTcpNatMapping.java:112)
    at de.fhkn.in.uce.connectivitymanager.investigator.DeterminingTcpNatMapping.executeTest(DeterminingTcpNatMapping.java:72)
    at de.fhkn.in.uce.connectivitymanager.investigator.InfrastructureInvestigatorImpl.investigateMappingBehavior(InfrastructureInvestigatorImpl.java:51)
    at de.fhkn.in.uce.connectivitymanager.investigator.InfrastructureInvestigatorImpl.investigateOwnNat(InfrastructureInvestigatorImpl.java:41)
    at de.fhkn.in.uce.connectivitymanager.manager.target.UnsecureTargetSideConnectionEstablishment.register(UnsecureTargetSideConnectionEstablishment.java:82)
    at de.fhkn.in.uce.connectivitymanager.manager.target.UnsecureTargetSideConnectionEstablishment.establishConnection(UnsecureTargetSideConnectionEstablishment.java:63)
    at de.fhkn.in.uce.connectivitymanager.demo.chat.Main.main(Main.java:32)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)

```

any idea why does it happens ? 

@72Zn 
@crusherd 

Thanks in advance
Roman

**Comment by helioit** [comment]
Hi Romanman
I have same problem as you. How to fix that ?
Help me !
